spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://192.168.177.114:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.177.114:8848
  application:
    name: gulimall-product

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 10000
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    cn.ayana.gulimall: debug
